server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hivantibodyscreening?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true